// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSctrpFFRzYcYiMy4IuS51fhtkYZRvRJM',
    appId: '1:1038439641750:web:3bc0bfd9968d86161848b7',
    messagingSenderId: '1038439641750',
    projectId: 'takemytrash',
    authDomain: 'takemytrash.firebaseapp.com',
    storageBucket: 'takemytrash.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVqAGTXYxs6XIc86pqxPzXm1jCONpIXCU',
    appId: '1:1038439641750:android:55b3aefdb8b805251848b7',
    messagingSenderId: '1038439641750',
    projectId: 'takemytrash',
    storageBucket: 'takemytrash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd6oc7onFo4dNBKXqNNwmb7B9sOto1ISI',
    appId: '1:1038439641750:ios:270ba7f0840be8651848b7',
    messagingSenderId: '1038439641750',
    projectId: 'takemytrash',
    storageBucket: 'takemytrash.firebasestorage.app',
    iosBundleId: 'com.example.takeMyTrash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd6oc7onFo4dNBKXqNNwmb7B9sOto1ISI',
    appId: '1:1038439641750:ios:270ba7f0840be8651848b7',
    messagingSenderId: '1038439641750',
    projectId: 'takemytrash',
    storageBucket: 'takemytrash.firebasestorage.app',
    iosBundleId: 'com.example.takeMyTrash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSctrpFFRzYcYiMy4IuS51fhtkYZRvRJM',
    appId: '1:1038439641750:web:42ed363c2a2c917f1848b7',
    messagingSenderId: '1038439641750',
    projectId: 'takemytrash',
    authDomain: 'takemytrash.firebaseapp.com',
    storageBucket: 'takemytrash.firebasestorage.app',
  );
}
